"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_expections.ipynb.

# %% ../nbs/00_expections.ipynb 2
from __future__ import annotations


# %% auto 0
__all__ = ['FeatureStoreException', 'ConfigurationError', 'ConnectionError', 'EntityError', 'FeatureViewError', 'ValidationError']

# %% ../nbs/00_expections.ipynb 3
class FeatureStoreException(Exception):
    """Base exception for feature store errors"""
    pass


# %% ../nbs/00_expections.ipynb 4
class ConfigurationError(FeatureStoreException):
    """Raised when there's an error in configuration"""
    pass


# %% ../nbs/00_expections.ipynb 5
class ConnectionError(FeatureStoreException):
    """Raised when there's an error connecting to Snowflake"""
    pass


# %% ../nbs/00_expections.ipynb 6
class EntityError(FeatureStoreException):
    """Raised when there's an error with entities"""
    pass


# %% ../nbs/00_expections.ipynb 7
class FeatureViewError(FeatureStoreException):
    """Raised when there's an error with feature views"""
    pass


# %% ../nbs/00_expections.ipynb 8
class ValidationError(FeatureStoreException):
    """Raised when there's a validation error"""
    pass

